// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rentals.sql

package database

import (
	"context"
	"database/sql"
)

const createRental = `-- name: CreateRental :one
INSERT INTO rentals (user_id, bike_id, status, start_latitude, start_longitude)
VALUES (
	?,
	?,
	'running',
	?,
	?
)
RETURNING id, user_id, bike_id, status, start_time, end_time, start_latitude, start_longitude, end_latitude, end_longitude, duration
`

type CreateRentalParams struct {
	UserID         int64
	BikeID         int64
	StartLatitude  sql.NullFloat64
	StartLongitude sql.NullFloat64
}

func (q *Queries) CreateRental(ctx context.Context, arg CreateRentalParams) (Rental, error) {
	row := q.db.QueryRowContext(ctx, createRental,
		arg.UserID,
		arg.BikeID,
		arg.StartLatitude,
		arg.StartLongitude,
	)
	var i Rental
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BikeID,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.StartLatitude,
		&i.StartLongitude,
		&i.EndLatitude,
		&i.EndLongitude,
		&i.Duration,
	)
	return i, err
}

const getRentalAdmin = `-- name: GetRentalAdmin :one
SELECT 
	rentals.bike_id,
	users.email AS user_email,
	users.first_name AS user_first_name,
	users.last_name AS user_last_name,
	rentals.status,
	rentals.start_time,
	rentals.end_time,
	rentals.start_latitude,
	rentals.start_longitude,
	rentals.end_latitude,
	rentals.end_longitude
FROM rentals
INNER JOIN users
	ON rentals.user_id = users.id
WHERE rentals.id = ?
`

type GetRentalAdminRow struct {
	BikeID         int64
	UserEmail      string
	UserFirstName  string
	UserLastName   string
	Status         string
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	StartLatitude  sql.NullFloat64
	StartLongitude sql.NullFloat64
	EndLatitude    sql.NullFloat64
	EndLongitude   sql.NullFloat64
}

func (q *Queries) GetRentalAdmin(ctx context.Context, id int64) (GetRentalAdminRow, error) {
	row := q.db.QueryRowContext(ctx, getRentalAdmin, id)
	var i GetRentalAdminRow
	err := row.Scan(
		&i.BikeID,
		&i.UserEmail,
		&i.UserFirstName,
		&i.UserLastName,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
		&i.StartLatitude,
		&i.StartLongitude,
		&i.EndLatitude,
		&i.EndLongitude,
	)
	return i, err
}

const listRentalsAdmin = `-- name: ListRentalsAdmin :many


SELECT 
	rentals.id AS rental_id,
	rentals.bike_id,
	users.email AS user_email,
	users.first_name AS user_first_name,
	users.last_name AS user_last_name,
	rentals.status,
	rentals.start_time,
	rentals.end_time,
	rentals.start_latitude,
	rentals.start_longitude,
	rentals.end_latitude,
	rentals.end_longitude
FROM rentals
INNER JOIN users
	ON rentals.user_id = users.id
ORDER BY rentals.start_time DESC
`

type ListRentalsAdminRow struct {
	RentalID       int64
	BikeID         int64
	UserEmail      string
	UserFirstName  string
	UserLastName   string
	Status         string
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	StartLatitude  sql.NullFloat64
	StartLongitude sql.NullFloat64
	EndLatitude    sql.NullFloat64
	EndLongitude   sql.NullFloat64
}

// the constraint in unique index for one running rental per user allows this query
// -------------------------------
// ADMIN
// -------------------------------
func (q *Queries) ListRentalsAdmin(ctx context.Context) ([]ListRentalsAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listRentalsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRentalsAdminRow
	for rows.Next() {
		var i ListRentalsAdminRow
		if err := rows.Scan(
			&i.RentalID,
			&i.BikeID,
			&i.UserEmail,
			&i.UserFirstName,
			&i.UserLastName,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
			&i.StartLatitude,
			&i.StartLongitude,
			&i.EndLatitude,
			&i.EndLongitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRentals = `-- name: ListUserRentals :many
SELECT 
		start_time,
		end_time,
		start_latitude,
		start_longitude,
		end_latitude,
		end_longitude
FROM rentals
WHERE user_id = ?
`

type ListUserRentalsRow struct {
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	StartLatitude  sql.NullFloat64
	StartLongitude sql.NullFloat64
	EndLatitude    sql.NullFloat64
	EndLongitude   sql.NullFloat64
}

func (q *Queries) ListUserRentals(ctx context.Context, userID int64) ([]ListUserRentalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRentals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRentalsRow
	for rows.Next() {
		var i ListUserRentalsRow
		if err := rows.Scan(
			&i.StartTime,
			&i.EndTime,
			&i.StartLatitude,
			&i.StartLongitude,
			&i.EndLatitude,
			&i.EndLongitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRentalAdmin = `-- name: UpdateRentalAdmin :exec
UPDATE rentals
SET 
	user_id = ?,
	bike_id = ?,
	status = ?,
	start_time = ?,
	end_time = ?,
	start_latitude = ?,
	start_longitude = ?,
	end_latitude = ?,
	end_longitude = ?
WHERE id = ?
`

type UpdateRentalAdminParams struct {
	UserID         int64
	BikeID         int64
	Status         string
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	StartLatitude  sql.NullFloat64
	StartLongitude sql.NullFloat64
	EndLatitude    sql.NullFloat64
	EndLongitude   sql.NullFloat64
	ID             int64
}

func (q *Queries) UpdateRentalAdmin(ctx context.Context, arg UpdateRentalAdminParams) error {
	_, err := q.db.ExecContext(ctx, updateRentalAdmin,
		arg.UserID,
		arg.BikeID,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
		arg.StartLatitude,
		arg.StartLongitude,
		arg.EndLatitude,
		arg.EndLongitude,
		arg.ID,
	)
	return err
}

const updateRentalToEnded = `-- name: UpdateRentalToEnded :exec
UPDATE rentals 
SET 
	status = 'ended',
	end_latitude = ?,
	end_longitude = ?
WHERE user_id = ? AND status = 'running'
`

type UpdateRentalToEndedParams struct {
	EndLatitude  sql.NullFloat64
	EndLongitude sql.NullFloat64
	UserID       int64
}

func (q *Queries) UpdateRentalToEnded(ctx context.Context, arg UpdateRentalToEndedParams) error {
	_, err := q.db.ExecContext(ctx, updateRentalToEnded, arg.EndLatitude, arg.EndLongitude, arg.UserID)
	return err
}
