// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package user

import (
	"database/sql"
)

type Bike struct {
	ID          int64
	IsAvailable sql.NullInt64
	Latitude    sql.NullFloat64
	Longitude   sql.NullFloat64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Rental struct {
	ID             int64
	UserID         int64
	BikeID         int64
	Status         string
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	StartLatitude  sql.NullFloat64
	StartLongitude sql.NullFloat64
	EndLatitude    sql.NullFloat64
	EndLongitude   sql.NullFloat64
	Duration       sql.NullInt64
}

type User struct {
	ID             int64
	Email          string
	HashedPassword string
	FirstName      string
	LastName       string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	IsAdmin        sql.NullInt64
}
